### ISSUE TITLE
Høytopplesing ved hjelp av Voice ASP

### ISSUE THREAD

**Issue by raae** [lesersokerbok/lsb-wpengine#219]
- [x] Lage egen knapperekke så deseignet matcher
- [x] Koble til apiet
- [x] Logge start/stopp eventer i google analytics

**Comment by raae** [comment]
Innlogging gjøre på http://control.leseweb.dk/

**Comment by raae** [comment]
<img width="720" alt="boksok_-_boker_til_alle_" src="https://user-images.githubusercontent.com/478531/27226415-3a6a948c-529f-11e7-9c96-977d360173fa.png">
